# Generated by Django 3.2.7 on 2021-10-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0003_remove_sociedadanonima_comformation_statute'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociedadanonima',
            name='comformation_statute',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterUniqueTogether(
            name='sociosa',
            unique_together={('partner', 'sa')},
        ),
    ]
