# Generated by Django 3.2.7 on 2021-10-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0006_alter_sociedadanonima_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociedadanonima',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
