version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=djangodb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - db-data:/var/lib/postgresql/data/
    ports: 
      - 5432:5432
  web:
    build: .
    container_name: django_DSSD
    command: gunicorn DSSD.wsgi:application --bind 0.0.0.0:8000
    container_name: django_DSSD
    environment:
      - DATABASE_URL
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
volumes: 
  db-data: