# Generated by Django 3.2.7 on 2021-11-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0009_sociedadanonima_case_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociedadanonima',
            name='numero_expediente',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
