# Generated by Django 3.2.7 on 2021-11-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0010_sociedadanonima_numero_expediente'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociedadanonima',
            name='drive_folder_link',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
