# Generated by Django 3.2.7 on 2021-12-01 22:55

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0011_sociedadanonima_drive_folder_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), default=list, size=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='sociedadanonima',
            name='export_countries',
        ),
        migrations.CreateModel(
            name='Exportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.CharField(max_length=4)),
                ('states', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='formulario.pais')),
                ('sa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='formulario.sociedadanonima')),
            ],
        ),
    ]
