# Generated by Django 3.2.7 on 2021-12-03 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0012_auto_20211201_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAHashes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=32, unique=True)),
                ('sa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.sociedadanonima')),
            ],
        ),
    ]
