# Generated by Django 3.2.7 on 2021-12-04 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0013_sahashes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lenguaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=20)),
                ('native_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='exportacion',
            old_name='continent',
            new_name='continent_code',
        ),
        migrations.AddField(
            model_name='exportacion',
            name='continent_name',
            field=models.CharField(default='continent', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pais',
            name='name',
            field=models.CharField(default='country', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pais',
            name='code',
            field=models.CharField(max_length=3),
        ),
        migrations.RemoveField(
            model_name='pais',
            name='languages',
        ),
        migrations.CreateModel(
            name='PaisLenguaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.pais')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.lenguaje')),
            ],
        ),
        migrations.AddField(
            model_name='pais',
            name='languages',
            field=models.ManyToManyField(through='formulario.PaisLenguaje', to='formulario.Lenguaje'),
        ),
    ]
