# Generated by Django 3.2.7 on 2021-12-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0014_auto_20211204_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociedadanonima',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
