# Generated by Django 3.2.7 on 2021-09-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociedadanonima',
            name='representative_email',
        ),
        migrations.AddField(
            model_name='socio',
            name='representative_email',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
