# Generated by Django 3.2.7 on 2021-10-01 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_auto_20210927_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociedadanonima',
            options={'ordering': ['-name']},
        ),
        migrations.RenameField(
            model_name='socio',
            old_name='representative_email',
            new_name='email',
        ),
        migrations.AddField(
            model_name='socio',
            name='is_representative',
            field=models.BooleanField(default=False),
        ),
    ]
