# Generated by Django 3.2.7 on 2021-10-02 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_auto_20211001_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociedadanonima',
            name='comformation_statute',
        ),
    ]
