# Generated by Django 3.2.7 on 2021-10-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0004_auto_20211001_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socio',
            name='email',
        ),
        migrations.AddField(
            model_name='sociedadanonima',
            name='representative_email',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
