# Generated by Django 3.2.7 on 2021-10-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0005_auto_20211001_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociedadanonima',
            name='creation_date',
            field=models.DateField(),
        ),
    ]
