# Generated by Django 3.2.7 on 2021-10-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0007_alter_sociedadanonima_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociedadanonima',
            name='stamp_hash',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
